#!/bin/bash
# Assumes ssh, git clones a repo from github
REPO=$1
shift
if [[ $REPO == *"/"* ]]
then
  git clone git@github.com:"$REPO" "$@"
else
  # Assume my github
  git clone git@github.com:ajay-gandhi/"$REPO" "$@"
fi
